-- MySQL Script generated by MySQL Workbench
-- Sun Nov 20 18:54:15 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema extra_virgin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `extra_virgin` ;

-- -----------------------------------------------------
-- Schema extra_virgin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `extra_virgin` DEFAULT CHARACTER SET utf8mb4 ;
USE `extra_virgin` ;

-- -----------------------------------------------------
-- Table `extra_virgin`.`menus`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `extra_virgin`.`menus` ;

CREATE TABLE IF NOT EXISTS `extra_virgin`.`menus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `file_name` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `extra_virgin`.`categories`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `extra_virgin`.`categories` ;

CREATE TABLE IF NOT EXISTS `extra_virgin`.`categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  `parent_id` INT NULL,
  `menu_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_category1_idx` (`parent_id` ASC),
  INDEX `fk_category_menu1_idx` (`menu_id` ASC),
  CONSTRAINT `fk_category_category1`
    FOREIGN KEY (`parent_id`)
    REFERENCES `extra_virgin`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_menu1`
    FOREIGN KEY (`menu_id`)
    REFERENCES `extra_virgin`.`menus` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `extra_virgin`.`body`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `extra_virgin`.`body` ;

CREATE TABLE IF NOT EXISTS `extra_virgin`.`body` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` TEXT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `extra_virgin`.`items`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `extra_virgin`.`items` ;

CREATE TABLE IF NOT EXISTS `extra_virgin`.`items` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `display_name` VARCHAR(45) NOT NULL,
  `context` TEXT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  `pice` DECIMAL(10,4) NOT NULL,
  `currency` VARCHAR(5) NOT NULL,
  `category_id` INT NOT NULL,
  `body_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_item_category1_idx` (`category_id` ASC),
  INDEX `fk_items_items1_idx` (`body_id` ASC),
  CONSTRAINT `fk_item_category1`
    FOREIGN KEY (`category_id`)
    REFERENCES `extra_virgin`.`categories` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_items_items1`
    FOREIGN KEY (`body_id`)
    REFERENCES `extra_virgin`.`body` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `extra_virgin`.`images`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `extra_virgin`.`images` ;

CREATE TABLE IF NOT EXISTS `extra_virgin`.`images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `alt_name` VARCHAR(45) NULL,
  `path` VARCHAR(255) NOT NULL,
  `display_order` INT(2) NULL,
  `item_id` INT NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_image_content_idx` (`item_id` ASC),
  CONSTRAINT `fk_image_content`
    FOREIGN KEY (`item_id`)
    REFERENCES `extra_virgin`.`items` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `extra_virgin`.`emails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `extra_virgin`.`emails` ;

CREATE TABLE IF NOT EXISTS `extra_virgin`.`emails` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(50) NOT NULL,
  `subject` VARCHAR(100) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `message` VARCHAR(255) NOT NULL,
  `created_at` DATETIME NULL,
  `updated_at` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `extra_virgin`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `extra_virgin`.`users` ;

CREATE TABLE IF NOT EXISTS `extra_virgin`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
